-- 코드를 입력하세요
SELECT
    EXTRACT(YEAR FROM O.SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM O.SALES_DATE) AS MONTH,
    COUNT(DISTINCT U.USER_ID) PUCHASED_USERS,
    ROUND(COUNT(DISTINCT U.USER_ID) / (SELECT
                                            COUNT (user_id) 
                                        FROM USER_INFO
                                        WHERE EXTRACT(YEAR FROM JOINED) IN '2021'), 1) PUCHASED_RATIO
FROM
(SELECT 
    *
FROM USER_INFO
WHERE EXTRACT(YEAR FROM JOINED) IN '2021') U, ONLINE_SALE O
WHERE U.USER_ID = O.USER_ID
GROUP BY EXTRACT(YEAR FROM O.SALES_DATE), EXTRACT(MONTH FROM O.SALES_DATE)
ORDER BY 1, 2